# Generated by Django 4.2 on 2023-05-12 07:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_blog_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="thumbnail",
            field=models.ImageField(upload_to="thumbnails"),
        ),
    ]
