# Generated by Django 4.2 on 2023-05-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="content",
        ),
    ]
