# Generated by Django 4.2 on 2023-05-12 05:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_blog_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=tinymce.models.HTMLField(max_length=50),
        ),
    ]
