# Generated by Django 4.2 on 2023-05-12 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_blog_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="thumbnail",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="thumbnails/%Y/%m/%d/"
            ),
            preserve_default=False,
        ),
    ]
